meta_title: "Bubba - Creating a community for new parents in busy cities "
meta_description: "Bubba is creating a community for new parents in busy cities"
meta_image: "resizedcover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards

